[WIP] Add french support
WFCD/WFinfo pull request #168
Opened 2021-04-17 01:06 UTC by dimon222

This is broken, don't bother merging until its working.

2021-04-23 19:08 UTC, KintonHiryuu commented
Line 126 - Regex triggers on é è ê  and so on, i updated it to this
`[^a-zàâçéèêëîïôûùüÿñæœ() 가-힣]`
and it seems to work better, but still not perfectly

2021-04-23 19:17 UTC, KintonHiryuu commented
seems like it struggle with systems tho, in `Ivara Prime Système Schéma` , it read `Ivara Prime stèmes Schéma` and print out the BP of Ivara - it seems like the only thing it struggles with tho, everything that's not systems (at least in my prime inventory) seems good

2021-04-23 19:21 UTC, KintonHiryuu requested changes
Change regex to
`[^a-zA-Zàâçéèêëîïôûùüÿñæœ가-힣]`

2026-04-26 03:31 UTC, dimon222 commented
Implemented in #413

2026-04-26 03:31 UTC, closed without merging